language: ruby
cache: bundler
env:
  - COVERAGE=true
rvm:
  - 2.4.2
before_script:
  - cp config/database.yml.mysql config/database.yml
  - bundle exec rake db:create db:migrate
  - npm install -g bower
  - bundle exec bowndler update
