login: &login
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  database: blog_development
  <<: *login

test:
  database: blog_test
  <<: *login

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  url: <%= ENV["MAS_BLOG_DATABASE_URL"] %>
