login: &login
  adapter: mysql2
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8
  username: blog


development:
  database: blog_development
  <<: *login

test:
  database: blog_test
  <<: *login

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  url: <%= ENV["MAS_BLOG_DATABASE_URL"] %>
